dwh:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DATASET') }}"
      keyfile: "{{ env_var('GCP_KEY_PATH') }}"
      threads: 4