{{ config(materialized='view', tags=['staging']) }}

select
    transaction_id,
    account_id,
    customer_id,
    merchant_id,
    cast(transaction_timestamp as timestamp) as transaction_timestamp,
    transaction_date,
    transaction_type,
    channel,
    amount,
    currency,
    merchant_category_code,
    merchant_name,
    merchant_city,
    merchant_state,
    merchant_country,
    payment_method,
    card_number_masked,
    authorization_code,
    processor_response_code,
    is_recurring,
    reference_transaction_id,
    customer_ip_address,
    customer_location_city,
    customer_location_state,
    customer_location_country,
    transaction_location_lat,
    transaction_location_lon,
    device_id,
    user_agent,
    session_id,
    ingestion_timestamp
from {{ source('stg','transactions') }}
